spring.application.name=web
spring.datasource.url = jdbc:postgresql://localhost:5432/tododeungjang_db
spring.datasource.username = localhost
spring.datasource.password = qorrla34
spring.jpa.database-platform = org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql = true
spring.jpa.hibernate.ddl-auto = update
